# Mass Spectrometry - Based Proteomics

This chapter is based on TODO: cytowanie do "Introduction to Mass Spectrometry-Based Proteomics" Matthiesen, Bunkenborg.
TODO: uzupełnić w oparciu o wykłady Dirka.

## MS-Based Proteomics Introduction

Mass spectrometry is one of the most important methods of studying proteins. 
It provides information that is complementary to information that can be obtained using techniques such as NMR or X-ray crystallography. 
Mass spectrometry is easier to automatate (and is more reproducible), more sensitive, can be used on complex mixtures and is easy to combine with different separation techniques. 
One of the main goals of MS-based Proteomics is identification and quantification of proteins and protein mixtures.
Post translational modifications resulting from many processes such as phosphorylation, acetylation or methylation can be analyzed by MS.
MS can be also used to determine N- or C-terminus of proteins to examine the primary structure of proteins or map proteolytic cleavage sites in proteins.
Moreover, MS can be applied to determine if the protein folded correctly and to other structural studies.

These notes focus on protein identification and quantification. 
There are three main approach to MS-based protein identification:

  - **bottom-up approach**, in which proteins are cut into peptides that serve as input to Mass Spectrometer,
  - **shotgun approach**, which is a special case of bottom-up proteomics where a complex mixture of proteins is digested into peptides (usually trypsin is used for this task) which are then separated using Liquid Chromatography,
  - **top-down approach**, in which the mass spectrometer isolates a full length protein (which can be fragmented inside the mass spectrometer and the masses of fragments can be also recorded).
 
TODO: work flow identyfikacji 
TODO: dobra ilustracja tych trzech strategii
TODO: co to jest LC? Co daje, co zmienia?

## Mass Spectrometer

A mass spectrometer is a device for measuring the mass-to-charge ratio of ionized molecules. 
All mass spectrometers consist of three main parts:
  - an ion source, where analyte ions are produced by transferring molecules from the condensed (liquid or solid) state to gas phase (ionization is done in the process and molecule can receive either positive or negative charge). Different methods can be used for ionization, most common in proteomics are ESI (Electro Spray Ionization) and MALDI (Matrix-Assisted Laser Desorption and Ionization),
  TODO: lepsze slowo niz "receive"
  - a mass analyzer, where the ions are separated according to their mass to charge ration (_m/z_). Multiple different types of analyzer exists and they can be used in combination (by tandem mass spectrometers)
  - a detector, which records a signal that can be electronically amplified and stored.
  TODO: opis detektora

TODO: dlaczego w ogole m/z jest pomocne.

The results from mass analyzers can be transformed to internsities as a function of _m/z_ (for example by Fourier Transform). The _m/z_ vs intensity plot is a mass spectrum that is the final output from the mass spectrometer.

Many combinations of instrument setups and fragmentation techniques can be used for MS-based Proteomics.
These choices affect the data analysis process, so understanding how the data were collected is crucial to protein identification and quantification.


## Sample Preparation

The quality of MS data depends on sample complexity and purity. 
Main issues are caused by
  - ion suppression, where many different species compete for the charges during the ionization process,
  TODO: wiecej, to jest tylko w LC czy ogolnie?
  - contamination associated with the mass spectrometer (for example oil used for mass spectrometer pumps), sample preparation in the lab (for example sheep keratin from clothing) or earlier sample preparation (for example serum used to supplement growth media when studying proteins from cell cultures). Even if contaminating proteins are included in the database query after MS experiment to avoid identifying proteins homologous to proteins from contamination, problems with ion suppresion or overlap with target peptides of interest may occur.
  
TODO: dodac ogolne uwagi z 2.2
Powiazac je z przykladami Dirka z trypsyna.

### Complete Digestion

Peptide and protein indentification methods are often robust against partial incomplete digestion. 
TODO: dodac przyklad z 2.3 z artykulu, o ile bedzie to zrozumiale.
On the other hand, some relative and absolute quantitation techniques are affected by uncontrolled digestion. 
The sensitive methods include iCAT, HysTag, iTRAQ and label free quantitation (relative measure); AQUA and QCONCAT (absolute quantification).
SILAC (relative) and PSAQ (absolute) are robust methods.

### Protein and Peptide Separation

For simple peptide sample is associated with less ion suppresion, which causes smaller risk of peak overlap and more sensitivity.
Protein and peptide separation techniques can be applied to obtain simple peptide mixtures. 

TODO: metody separacji z 2.4, o ile to bedzie zrozumiale, ew. powiazac z wykladami Dirka

Before LC-MS, the peptide sample is usually cleaned up (desalted and cleaned from gel debris) by reversed phase columns.

TODO: co to jest column <...> ?

## Ionization Methods and Mass Analyzers

The formation of gas-phase ions is required before the molecular masses of a sample can be measured by the mass analyzer. 
ESI and MALDI are two methods that are able to eficiently create the ions from large biomolecules with minimum fragmentation.
Currently, five mass analyzer types are commonly used: quadrupole mass filters (Q), time of flight mass analyzers (TOF), ion traps (IT), FT-ICR and Orbitrap analyzers.
They can work as standalone but they are usually combined in hybrid configurations of which some are more popular. 
The most populars configurations include Q-TOF, Q-ion mobility-TOF, triple quadrupole, ion trap-Orbitrap and Q-Orbitrap.


### MALDI-TOF MS

#### MALDI Ionization

In MALDI, the analyte is mixed with a compound (called the matrix, usually small aromatic acids), which absorbs the energy from the laser. 
The sample is co-crystallized with an excess amount of the matrix.
Irradiation with a short-pulsed laser causes mainly ionization of the matrix followed by energy and proton transfer to the analyte.
MALDI efficiently ionizes peptides and protein intact.
This method is robust t typical contaminants present in protein/peptide samples such as salts, urea or glycerol, though it is sensitive to low concentrations of SDS.

Matrix preparation affects the quality of MALDI-MS spectra.
There is no universal matrix preparation procedure.
While several general guidelines have been found, several combinations should be tested for each sample and some optimization specific to the sample may be needed.

TODO: jasniejszy/bardziej szczegolowy opis

TODO: co to dokladnie PMF?

#### The TOF Mass Analyzer

In TOF-MS a population of ions, for example derived by MALDI, is accelerated by an eletrical potential and each ion acquires a kinetic energy depending on its mass and charge state.
After acceleration the ions pass through a field free region where each ion is traveling with a speed characteristic of their _m/z_ value.
At the end of the field free regiona detector measures the time of flight (TOF).
TOF is a sum of flight times in two regions - accelaration region and field free region - and detection time.
TOF in field free region can be estimated by the drift time, which is proportional to the square root of _m/z_.

TODO: wzor na drift time

TODO: uwagi nt mass resolution (tu lub gdzies indziej)


#### MALDI-TOF MS Spectrum

TOF recored by MALDI-TOF spectrometer must be transformed to relative intensity.


#### MALDI-TOF MS Issues

Issues with MALDI include the fact that some peptides may not be able to co-crystallize with the used matrix and arginine-containing peptides are more frequently observed in MALDI MS spectra due to higher proton affinity and higher stability. 
Due to the competition for the protons in the matrix plume, a limited protein sequence coverage is observed (30-40% in good samples).
Moreover, heterogenity in the matrix-sample sample crystal formation can cause difficulties for quantifying and reproducing results.
The major problem with MALDI-TOF MS is obtaining highly significant search results due to not all expected tryptic peptides showing up in experimental MS spectrum and presence of unknown mass peaks.
PMF is limited to the analysis of purified proteins.


## Fragmentation Methods


## Detectors


## MS-MS Spectra

